POST http://localhost:8080/requests
Content-Type: application/json

{
  "id": "012043-05",
  "idFile": "5a6c2a39-790e-47a2-9602-477d2b5ecbd4",
  "title": "Тест",
  "fromUser": "Ivan Dragunov",
  "toUsers": [
    "Глеб Никишин"
  ]
}
